// todo-list-item.jsx
import React from 'react';
import styled from 'styled-components';
import StyleButton from './style-button.jsx';

const Template = styled.template`
.remove-button{
  color: orangered;
}
`
export default class TodoListItem extends React.Component{
  render(){
    return (
      <Template>
        <li>
          { this.props.todo.text }
          <StyleButton
            className={"remove-button"}
            onClick={()=>this.props.remove(this.props.todo.id)}
          >
            X
          </StyleButton>
        </li>
      </Template>
    )
  }
}

// todo-list-item.vue
<style lang="scss" scoped>
.remove-button{
  color: orangered;
}
</style>
<script>
import StyleButton from './style-button.vue'
export default {
  components: { StyleButton },
  props: {
    todo: {
      type: Object,
      required: true
    }
  }
}
</script>
<template>
  <li>
    {{ todo.text }}
    <style-button
      class="remove-button"
      @click="$emit('remove', todo.id)"
    >
      X
    </style-button>
  </li>
</template>
