// todo-list.jsx
import React from "react";
import styled from "styled-components";

import BaseInputText from './base-input-text.jsx'
import TodoListItem from './todo-list-item.jsx'

const Template = styled.template`
`

let nextTodoId = 1

export default class TodoList extends React.Component{

  state = {
    newTodoText: '',
    todos: [
      {
        id: nextTodoId++,
        text: 'Learn Vue'
      },
      {
        id: nextTodoId++,
        text: 'Learn about single-file components'
      },
      {
        id: nextTodoId++,
        text: 'Fall in love'
      }
    ]
  }

  setNeTodoText = (value) => {
    this.setState({ newTodoText });
  }

  addTodo = () => {
    const trimmedText = this.state.newTodoText.trim()
    if (trimmedText) {
      this.setState({
        todos: this.state.todos.concat([{
          id: nextTodoId++,
          text: trimmedText
        }])
      })
      this.setState({newTodoText: ''})
    }
  },

  removeTodo = (idToRemove) => {
    this.setState({
      todos: this.state.todos.filter(todo => {
        return todo.id !== idToRemove
      })
    })
  }

  render(){
    return (
      <Template>
        <div>
          <BaseInputText 
            value={this.state.newTodoText}
            placeholder="New todo"
            onChange={this.setNeTodoText}
            onEnter={this.addTodo}
          />
          {todos.length && 
            <ul>
              {this.state.todos.map(todo=>
                <TodoListItem
                  key={todo.id}
                  todo={todo}
                  remove={this.removeTodo}
                />
              )}
            </ul>
          }
          <p v-else>
            Nothing left in the list. Add a new todo in the input above.
          </p>
        </div>
      </Template>
    )
  };
}

// todo-list.vue
<script>
import BaseInputText from './base-input-text.vue'
import TodoListItem from './todo-list-item.vue'

let nextTodoId = 1

export default {

	components: {
		BaseInputText, TodoListItem
  },
  
  data () {
    return {
			newTodoText: '',
      todos: [
				{
					id: nextTodoId++,
					text: 'Learn Vue'
				},
				{
					id: nextTodoId++,
					text: 'Learn about single-file components'
				},
				{
					id: nextTodoId++,
					text: 'Fall in love'
				}
			]
    }
  },
  
	methods: {
		addTodo () {
			const trimmedText = this.newTodoText.trim()
			if (trimmedText) {
				this.todos.push({
					id: nextTodoId++,
					text: trimmedText
				})
				this.newTodoText = ''
			}
		},
		removeTodo (idToRemove) {
			this.todos = this.todos.filter(todo => {
				return todo.id !== idToRemove
			})
		}
	}
}
</script>
<template>
	<div>
		<BaseInputText 
			v-model="newTodoText"
			placeholder="New todo"
			@keydown.enter="addTodo"
		/>
		<ul v-if="todos.length">
			<TodoListItem
				v-for="todo in todos"
				:key="todo.id"
				:todo="todo"
				@remove="removeTodo"
			/>
		</ul>
		<p v-else>
			Nothing left in the list. Add a new todo in the input above.
		</p>
	</div>
</template>
